name: WeChat Backup
on:
  schedule:
    - cron: "0 13 * * *"     # 每天 21:00（UTC+8）
  workflow_dispatch: {}

permissions:
  contents: write   # 仅授予提交权限

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run backup
        env:
          WECHAT_APPID: ${{ secrets.WECHAT_APPID }}
          WECHAT_APPSECRET: ${{ secrets.WECHAT_APPSECRET }}
          WECHAT_ACCOUNT_NAME: "文不加点的张衔瑜"
        run: python scripts/backup_wechat.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: sync wechat articles"
          file_pattern: |
            content/**/*.md
            assets/**/*
            data/snapshots/**/*.json
