name: WeChat Backup
on:
  schedule:
    - cron: "0 7 * * 2" # 每周二 07:00 UTC 运行（北京时间 15:00）
  workflow_dispatch: {}

permissions:
  contents: write         # 推送提交
  pull-requests: write    # 创建/更新 PR 需要该权限

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Create feature branch for this run
        run: |
          BRANCH="backup/run-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Run backup
        run: |
          python scripts/backup_wechat.py \
            --appid "${{ secrets.WECHAT_APPID }}" \
            --secret "${{ secrets.WECHAT_APPSECRET }}" \
            --account-name "文不加点的张衔瑜" # (user need to change this to the actual account name)

      - name: Commit & Push
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: sync wechat articles"
            git push -u origin "$BRANCH"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Open Pull Request
        if: steps.commit.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync wechat articles"
          branch: ${{ env.BRANCH }}
          title: "WeChat backup: ${{ env.BRANCH }}"
          body: "Automated backup run. Please review changes."
          base: master
